### ISSUE TITLE
eljur_notifier.csproj.user

### ISSUE THREAD

**Issue by AndreyPonyakov** [spartacusxxxxxx/eljur_notifier#1]
хранить не нужно. Добавь его в .gitignore и удали с гита

**Comment by AndreyPonyakov** [comment]
сорри имел ввиду eljur_notifier.csproj.user

**Comment by spartacus1988** [comment]
Удалил из текущего коммита, но в более ранних зачищать не стал, вроде бы там ничего секретного нет. А в чём проблема с этим файлом? Студия ругается на чужие настройки?

**Comment by AndreyPonyakov** [comment]
это твои личные локальные настройки студии, типа какие окошки открыты в последнем сеансе, лайаут и тд. Просто мусор с точки зрения контроля версий
